export const countries = [
    { code: 'AF', label: 'Afghanistan', phone: '93', emoji: '🇦🇫' },
    { code: 'AL', label: 'Albania', phone: '355', emoji: '🇦🇱' },
    { code: 'DZ', label: 'Algeria', phone: '213', emoji: '🇩🇿' },
    { code: 'AS', label: 'American Samoa', phone: '1', emoji: '🇦🇸' },
    { code: 'AD', label: 'Andorra', phone: '376', emoji: '🇦🇩' },
    { code: 'AO', label: 'Angola', phone: '244', emoji: '🇦🇴' },
    { code: 'AI', label: 'Anguilla', phone: '1', emoji: '🇦🇮' },
    { code: 'AR', label: 'Argentina', phone: '54', emoji: '🇦🇷' },
    { code: 'AM', label: 'Armenia', phone: '374', emoji: '🇦🇲' },
    { code: 'AU', label: 'Australia', phone: '61', emoji: '🇦🇺' },
    { code: 'AT', label: 'Austria', phone: '43', emoji: '🇦🇹' },
    { code: 'AZ', label: 'Azerbaijan', phone: '994', emoji: '🇦🇿' },
    { code: 'BH', label: 'Bahrain', phone: '973', emoji: '🇧🇭' },
    { code: 'BD', label: 'Bangladesh', phone: '880', emoji: '🇧🇩' },
    { code: 'BY', label: 'Belarus', phone: '375', emoji: '🇧🇾' },
    { code: 'BE', label: 'Belgium', phone: '32', emoji: '🇧🇪' },
    { code: 'BR', label: 'Brazil', phone: '55', emoji: '🇧🇷' },
    { code: 'CA', label: 'Canada', phone: '1', emoji: '🇨🇦' },
    { code: 'CN', label: 'China', phone: '86', emoji: '🇨🇳' },
    { code: 'CO', label: 'Colombia', phone: '57', emoji: '🇨🇴' },
    { code: 'FR', label: 'France', phone: '33', emoji: '🇫🇷' },
    { code: 'DE', label: 'Germany', phone: '49', emoji: '🇩🇪' },
    { code: 'IN', label: 'India', phone: '91', emoji: '🇮🇳' },
    { code: 'ID', label: 'Indonesia', phone: '62', emoji: '🇮🇩' },
    { code: 'IR', label: 'Iran', phone: '98', emoji: '🇮🇷' },
    { code: 'IQ', label: 'Iraq', phone: '964', emoji: '🇮🇶' },
    { code: 'IE', label: 'Ireland', phone: '353', emoji: '🇮🇪' },
    { code: 'IL', label: 'Israel', phone: '972', emoji: '🇮🇱' },
    { code: 'IT', label: 'Italy', phone: '39', emoji: '🇮🇹' },
    { code: 'JP', label: 'Japan', phone: '81', emoji: '🇯🇵' },
    { code: 'MY', label: 'Malaysia', phone: '60', emoji: '🇲🇾' },
    { code: 'MX', label: 'Mexico', phone: '52', emoji: '🇲🇽' },
    { code: 'NL', label: 'Netherlands', phone: '31', emoji: '🇳🇱' },
    { code: 'NZ', label: 'New Zealand', phone: '64', emoji: '🇳🇿' },
    { code: 'PK', label: 'Pakistan', phone: '92', emoji: '🇵🇰' },
    { code: 'PH', label: 'Philippines', phone: '63', emoji: '🇵🇭' },
    { code: 'PT', label: 'Portugal', phone: '351', emoji: '🇵🇹' },
    { code: 'QA', label: 'Qatar', phone: '974', emoji: '🇶🇦' },
    { code: 'RU', label: 'Russia', phone: '7', emoji: '🇷🇺' },
    { code: 'SA', label: 'Saudi Arabia', phone: '966', emoji: '🇸🇦' },
    { code: 'SG', label: 'Singapore', phone: '65', emoji: '🇸🇬' },
    { code: 'ZA', label: 'South Africa', phone: '27', emoji: '🇿🇦' },
    { code: 'ES', label: 'Spain', phone: '34', emoji: '🇪🇸' },
    { code: 'LK', label: 'Sri Lanka', phone: '94', emoji: '🇱🇰' },
    { code: 'SE', label: 'Sweden', phone: '46', emoji: '🇸🇪' },
    { code: 'CH', label: 'Switzerland', phone: '41', emoji: '🇨🇭' },
    { code: 'AE', label: 'UAE', phone: '971', emoji: '🇦🇪' },
    { code: 'GB', label: 'United Kingdom', phone: '44', emoji: '🇬🇧' },
    { code: 'US', label: 'United States', phone: '1', emoji: '🇺🇸' },
];
